# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8ce4d025cf5cac56ca24dfce2c807a313ff245757002390ab1fd821778eef14e37e785ca8d9665708461c802e852feb31894618977b2199b3d773a0ac1b1a679

test:
  secret_key_base: c0f20f3173ac4d78876546d9c3fe73d1c4c41dfcdfc0554218639acc228fe0b8f743c47df1629f96b26f59aa17e4d34ff1bd3b58c8c4b5b571ec6dafe33a75f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
